#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(NICTA_GPL)
#

TARGETS := $(notdir ${SOURCE_DIR}).cdl
ADL := testrpccall.camkes

Client_CFILES := src/client.c
Echo_CFILES := src/echo.c
Poke_CFILES := src/poke.c

include ${PWD}/tools/camkes/camkes.mk
