#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(NICTA_GPL)
#

# This file is build system boiler plate for describing library dependencies.
# You can safely ignore it unless this application needs to depend on some
# extra unusual libraries.

apps-$(CONFIG_APP_ULTTERMINAL) += ultterminal
ultterminal: libsel4 libmuslc libsel4muslccamkes libsel4camkes libsel4sync libsel4debug libsel4bench libringbuffer
